### ISSUE TITLE
What color scheme is used in the example?

### ISSUE THREAD

**Issue by mariusju** [zperrault/vimrc.js#10]

**Comment by sloanelybutsurely** [comment]
https://github.com/morhetz/gruvbox is the color scheme used in all of the screenshots. Specifically with True Color and italics enabled. 

I have been considering bundling https://github.com/joshdick/onedark.vim to continue the "Atom replacement" philosophy of this project.

**Comment by mariusju** [comment]
thank you for the answer :)
