### ISSUE TITLE
Issue when saving .js files

### ISSUE THREAD

**Issue by eanplatter** [zperrault/vimrc.js#13]
Was previously a neovim user using Vundle for plugin management, ran the curl command in the readme and got this when trying to save a `.js` file. This doesn't seem to happen on other filetypes.
## Screenshot:

![screen shot 2016-09-21 at 9 03 38 am](https://cloud.githubusercontent.com/assets/3782604/18714954/07441262-7fdd-11e6-9016-bfe14a1ddacb.png)

**Comment by gabrielhpugliese** [comment]
Happens to me too, but strange thing that I have installed eslint globally with `npm -g i eslint`

**Comment by eanplatter** [comment]
Oh nice I will test out #14

**Comment by eanplatter** [comment]
Having eslint installed globally makes it work.
