### ISSUE TITLE
Use YouCompleteMe for vim and neovim

### ISSUE THREAD

**Issue by renatoagds** [zperrault/vimrc.js#19]
Hi!

I want to open this issue to propose we use YouCompleteMe for `vim` and `neovim`.

_Why ?_

In the last month I resolved to use `deoplete` after use `YouCompleteMe` for a lot of months, and I found a few points that `YouCompleteMe` is much better.

**Folder Completion**

YouCompleteMe uses the opened file path as base to propose the completion and deoplete use the  path that you started `vim/neovim` as base, that is a big difference between you `import` something wrong.

**Small Docs**

YouCompleteMe gives to you an small explanation about the function that you will use.

_Performance ?_

In one month using `deoplete` I didn't feel any difference in performance between it and `YouCompleteMe`.

**Comment by eanplatter** [comment]
Hey @renatoagds would you mind making a PR with this? I'd like to see what the change looks like.

**Comment by renatoagds** [comment]
@eanplatter sure! I'll do that asap. 👍

**Comment by davidosomething** [comment]
ternjs is what provides the signature in completion (screenshot of my setup with deoplete: http://screencast.com/t/I1sA4WRxHWQ)

**Comment by davidosomething** [comment]
deoplete has an option to set basepath for where file completion starts from: https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L324

this should really be a personal preference, you can always `:cd` to where you want to be

**Comment by renatoagds** [comment]
@davidosomething nice! so, I think we can set `deoplete#file#enable_buffer_path` as 1 by default, IMO.
