### ISSUE TITLE
Installation didn't work

### ISSUE THREAD

**Issue by ezralalonde** [zperrault/vimrc.js#2]
Hi,

More of an FYI than anything, but I got:

```
git clone --quiet git@github.com:zperrault/vimrc.js.git ~/.vimrc.js
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Changing the script to have `git clone --quiet https://github.com/zperrault/vimrc.js.git ~/.vimrc.js` instead worked for me.

Thanks for the effort! I'm really looking forward to trying vimrc.js out.

Cheers,
Ezra.

**Comment by barbaraliau** [comment]
I had this same issue and this fixed it. Thanks.

**Comment by sloanelybutsurely** [comment]
Hi @ezralalonde! Thanks for opening this issue. It looks like the ssh url won't work if you don't have ssh keys setup in github. I'll update the install script with your suggested change!
