### ISSUE TITLE
How to show eslint errors along with coding like it in atom?

### ISSUE THREAD

**Issue by Axighi** [zperrault/vimrc.js#6]

**Comment by megalithic** [comment]
I haven't looked through everything in this repo yet, but I use Neomake to do async linting errors in the gutter. I don't use Atom, so I don't know what/how it derives or presents linting errors. Neomake works great for me.

**Comment by megalithic** [comment]
I use neovim, but i'm sure neomake will start working just fine with vim8

**Comment by sloanelybutsurely** [comment]
@Axighi Could you elaborate a bit on what you'd like to happen?

**Comment by Axighi** [comment]
@zperrault like this:
![screen shot 2016-09-18 at 10 07 43](https://cloud.githubusercontent.com/assets/1728926/18612262/d56c3258-7d87-11e6-8b60-207c077369ed.png)

**Comment by sloanelybutsurely** [comment]
@Axighi Thanks to #7 we are now using Neomake for linting errors in Neovim.

There are a couple of things that Atom does.
1. Linting of the unsaved buffer
   - I'm not sure if I event want to emulate this behavior. It seems a bit heavy handed to me.
2. Displaying linting errors as tooltips
   - This might be possible in something like MacVim or gVim but I think it a bit out of the scope of this project.

If you're looking for unsaved buffer linting, I think I can safely say I won't be supporting that. However, I can take a look at tooltips for things like gVim and MacVim. Although, it is getting to be a bit of a pain to maintain two copies of things, one for vanilla vim and one for neovim.

Also, @Axighi, if you're interested in working on this let me know. I'd be happy to review a PR that adds the feature you're looking for.
