### ISSUE TITLE
How are you getting tern to auto magically show

### ISSUE THREAD

**Issue by chopfitzroy** [zperrault/vimrc.js#9]
I use tern and deoplete in my local set up and I have been trying for ages to nicely get the deoplete to automatically show suggestions without using: `<C-x><C-o>`.

I took a quick squiz at your `vimrc` but I wondered if you would mind quickly elaborating on exactly what is going on there?

Cheers.

**Comment by sloanelybutsurely** [comment]
I believe SuperTab is what's causing the suggestions to display while typing.

**Comment by sloanelybutsurely** [comment]
https://github.com/ervandew/supertab

**Comment by chopfitzroy** [comment]
Hey @zperrault sweet as thank you :)
